
---
openapi: 3.0.0
info:
  title: Badge Access
  description: "## Accredit API for retrieving badge access data\n\nFor authorisation, please provide a valid bearer token in your request.\nIf you do not have one, please refer to our \n  [Auth Token Endpoint Documentation](https://app.swaggerhub.com/apis-docs/ACCREDIT/Auth/1.0.0).\n"
  version: 3.0.0
servers:
- url: https://demo2022-uat-api.accredit-solutions.com
security:
- bearerAuth: []
paths:
  /api/v3.0/badgeAccess:
    get:
      tags:
      - v3.0
      summary: List badge access details
      description: |
        Fetch details data about all available badge access.
      responses:
        "200":
          description: Badge access details
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ListBadgeAccessResponse'
        "401":
          description: "Unauthorised: Access token is missing or invalid"
  /api/v3.0/badgeAccess/{badgeAccessId}:
    get:
      tags:
      - v3.0
      summary: Get badge access details
      description: |
        Fetch detailed data about an existing badge access.
      parameters:
      - name: badgeAccessId
        in: path
        required: true
        schema:
          type: string
          format: uuid
      responses:
        "200":
          description: Badge access details
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/GetBadgeAccessResponse'
        "401":
          description: "Unauthorised: Access token is missing or invalid"
        "404":
          description: "Not Found: The specified resource cannot be found"
components:
  schemas:
    ListBadgeAccessResponse:
      type: object
      properties:
        BadgeAccess:
          type: array
          items:
            $ref: '#/components/schemas/BadgeAccessDetails'
      allOf:
      - $ref: '#/components/schemas/BaseResponse'
    GetBadgeAccessResponse:
      type: object
      allOf:
      - $ref: '#/components/schemas/BadgeAccessDetails'
      - $ref: '#/components/schemas/BaseResponse'
    BadgeAccessDetails:
      type: object
      properties:
        Id:
          type: string
          format: uuid
        Name:
          type: string
        Code:
          type: string
        Description:
          type: string
        LastUpdated:
          type: string
          format: date-time
        CreatedDate:
          type: string
          format: date-time
    BaseResponseWithErrors:
      properties:
        HttpStatusCode:
          type: integer
          description: The HTTPStatusCode of the response
          example: 400
        Errors:
          type: array
          description: List of error details; may not be comprehensive if an early exception occurs during request processing.
          items:
            $ref: '#/components/schemas/ErrorDetails'
    ErrorDetails:
      type: object
      properties:
        DataElement:
          type: string
          description: "Specifies the request field that caused the error, if applicable."
        Error:
          type: string
          description: "A descriptive explanation of the error, if available."
        ErrorCode:
          type: string
          description: The Accredit error code. Please refer to our error code documentation for further detail
        ValueProvided:
          type: string
          description: "Specifies the request value that caused the error, if applicable."
    BaseResponse:
      type: object
      properties:
        HttpStatusCode:
          type: integer
          description: The HTTPStatusCode of the response
          example: 200
  responses:
    BadRequest:
      description: Bad Request
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/BaseResponseWithErrors'
    UnauthorizedError:
      description: "Unauthorised: Access token is missing or invalid"
  parameters:
    BadgeZipFileId:
      name: badgeZipFileId
      in: path
      required: true
      style: simple
      explode: false
      schema:
        type: string
        format: uuid
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer