---
openapi: 3.0.0
info:
  title: Matrix
  description: "## Accredit API for retrieving matrix data\n\nFor authorisation, please provide a valid bearer token in your request.\nIf you do not have one, please refer to our \n  [Auth Token Endpoint Documentation](https://app.swaggerhub.com/apis-docs/ACCREDIT/Auth/1.0.0).\n"
  version: 3.0.0
servers:
- url: https://demo2022-uat-api.accredit-solutions.com
  description: SwaggerHub API Auto Mocking
security:
- bearerAuth: []
paths:
  /api/v3.0/matrix:
    get:
      tags:
      - v3.0
      summary: List matrix details
      description: |
        Fetch details data about all available matrices.
      parameters:
      - name: functionalAreaId
        description: Filter results by event account type.
        in: query
        schema:
          type: string
          format: uuid
      - name: roleId
        description: Filter results by registration subtype.
        in: query
        schema:
          type: string
          format: uuid
      - name: registrationTypeId
        description: Filter results by registration type.
        in: query
        schema:
          type: string
          format: uuid
      responses:
        "200":
          description: Matrix details
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ListMatrixResponse'
        "401":
          description: "Unauthorised: Access token is missing or invalid"
  /api/v3.0/matrix/{matrixId}:
    get:
      tags:
      - v3.0
      summary: Get matrix details
      description: |
        Fetch detailed data about an existing matrix.
      parameters:
      - name: matrixId
        in: path
        required: true
        schema:
          type: string
          format: uuid
      responses:
        "200":
          description: Matrix details
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/GetMatrixResponse'
        "401":
          description: "Unauthorised: Access token is missing or invalid"
        "404":
          description: "Not Found: The specified resource cannot be found"

components:
  schemas:
    ListMatrixResponse:
      type: object
      properties:
        Matrices:
          type: array
          items:
            $ref: '#/components/schemas/MatrixDetails'
      allOf:
      - $ref: '#/components/schemas/BaseResponse'

    GetMatrixResponse:
      type: object
      allOf:
      - $ref: '#/components/schemas/MatrixDetails'
      - $ref: '#/components/schemas/BaseResponse'
    
    MatrixDetails:
      type: object
      properties:
        Id:
          type: string
          format: uuid
        Name:
          type: string
        Entries:
          type: array
          items:
            type: object
            properties:
              Role:
                type: object
                properties:
                  Id:
                    type: string
                    format: uuid
                  Name:
                    type: string
              RegistrationType:
                type: object
                properties:
                  Id:
                    type: string
                    format: uuid
                  Name:
                    type: string
              FunctionalArea:
                type: object
                properties:
                  Id:
                    type: string
                    format: uuid
                  Name:
                    type: string
          
    BaseResponseWithErrors:
      properties:
        HttpStatusCode:
          type: integer
          description: The HTTPStatusCode of the response
          example: 400
        Errors:
          type: array
          description: List of error details; may not be comprehensive if an early exception occurs during request processing.
          items:
            $ref: '#/components/schemas/ErrorDetails'
    ErrorDetails:
      type: object
      properties:
        DataElement:
          type: string
          description: "Specifies the request field that caused the error, if applicable."
        Error:
          type: string
          description: "A descriptive explanation of the error, if available."
        ErrorCode:
          type: string
          description: The Accredit error code. Please refer to our error code documentation for further detail
        ValueProvided:
          type: string
          description: "Specifies the request value that caused the error, if applicable."
    BaseResponse:
      type: object
      properties:
        HttpStatusCode:
          type: integer
          description: The HTTPStatusCode of the response
          example: 200
  
  responses:
    BadRequest:
      description: Bad Request
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/BaseResponseWithErrors'
    UnauthorizedError:
      description: "Unauthorised: Access token is missing or invalid"
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
