---
openapi: 3.0.0
info:
  title: Registration Status
  description: "## Accredit API for retrieving registration status data\n\nFor authorisation, please provide a valid bearer token in your request.\nIf you do not have one, please refer to our \n  [Auth Token Endpoint Documentation](https://app.swaggerhub.com/apis-docs/ACCREDIT/Auth/1.0.0).\n"
  version: 3.0.0
servers:
- url: https://demo2022-uat-api.accredit-solutions.com
security:
- bearerAuth: []
paths:
  /api/v3.0/registrationStatus:
    get:
      tags:
      - v3.0
      summary: registrationStatus
      description: |
        Fetch details data about all available registration statuses.
      responses:
        "200":
          description: Registration status details
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ListRegistrationStatusResponse'
        "401":
          description: "Unauthorised: Access token is missing or invalid"
  /api/v3.0/registrationStatus/{registrationStatusCode}:
    get:
      tags:
      - v3.0
      summary: registrationStatus/{registrationStatusCode}
      description: |
        Fetch detailed data about an existing registration status.
      parameters:
      - name: registrationStatusCode
        in: path
        required: true
        schema:
          type: string
      responses:
        "200":
          description: Registration status details
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/GetRegistrationStatusResponse'
        "401":
          description: "Unauthorised: Access token is missing or invalid"
        "404":
          description: "Not Found: The specified resource cannot be found"
components:
  schemas:
    ListRegistrationStatusResponse:
      type: object
      properties:
        RegistrationStatuses:
          type: array
          items:
            $ref: '#/components/schemas/RegistrationStatusDetails'
      allOf:
      - $ref: '#/components/schemas/BaseResponse'
    GetRegistrationStatusResponse:
      type: object
      allOf:
      - $ref: '#/components/schemas/RegistrationStatusDetails'
      - $ref: '#/components/schemas/BaseResponse'
    RegistrationStatusDetails:
      type: object
      properties:
        Code:
          type: string
        Name:
          type: string
    BaseResponseWithErrors:
      properties:
        HttpStatusCode:
          type: integer
          description: The HTTPStatusCode of the response
          example: 400
        Errors:
          type: array
          description: List of error details; may not be comprehensive if an early exception occurs during request processing.
          items:
            $ref: '#/components/schemas/ErrorDetails'
    ErrorDetails:
      type: object
      properties:
        DataElement:
          type: string
          description: "Specifies the request field that caused the error, if applicable."
        Error:
          type: string
          description: "A descriptive explanation of the error, if available."
        ErrorCode:
          type: string
          description: The Accredit error code. Please refer to our error code documentation for further detail
        ValueProvided:
          type: string
          description: "Specifies the request value that caused the error, if applicable."
    BaseResponse:
      type: object
      properties:
        HttpStatusCode:
          type: integer
          description: The HTTPStatusCode of the response
          example: 200
  responses:
    BadRequest:
      description: Bad Request
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/BaseResponseWithErrors'
    UnauthorizedError:
      description: "Unauthorised: Access token is missing or invalid"
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
